language: python
dist: trusty
git:
  submodules: false

python:
    - 3.6

script:
    - travis_retry pip install --upgrade pip setuptools wheel
    - travis_retry pip install -r requirements.txt --only-binary=scipy

sudo: false
